FROM  debian:11
RUN   apt-get -y update && apt-get --y upgrade
RUN   apt-get -y install wget
RUN apt-get -y install php common && php-fpm && php-mysql && apt install curl -y
RUN sed -i  's/listen = \/run\/php\/php7.3-fpm.sock/listen = 9000/g' /etc/php/7.3/fpm/pool.d/www.conf
RUN wget https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
RUN chmod +x wp-cli.phar
RUN mv wp-cli.phar /usr/local/bin/wp
WORKDIR /var/www/html
COPY ./tools/script.sh /
EXPOSE 9000
CMD ["./script.sh"]



