version : '3'

services:
  nginx:
    hostname: nginx
    build:
      context: ./requirements/nginx
      # dockerfile: ./nginx/Dockerfile
    depends_on:
      - wordpress
    ports:
      - "443:443"
    restart: always
    volumes:
      - wordpress:/var/www/html
    env_file:
      - .env
    networks:
      - inception
    

  mariadb:
    hostname: mariadb
    build:
      context: ./requirements/mariadb
      # dockerfile: ./mariadb/Dockerfile
    restart: always
    volumes:
      - mariadb:/var/lib/mysql
    env_file:
      - .env
    networks:
      - inception
    #Par défaut, MariaDB utilise le port 3306 pour les connexions TCP/IP.

  wordpress:
    hostname: wordpress
    build:
      context: ./requirements/wordpress
      # dockerfile: ./wordpress/Dockerfile
    restart: always
    volumes:
      - wordpress:/var/www/html/
    env_file:
      - .env
    depends_on:
      - mariadb
    networks:
      - inception

volumes:
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/mmakboub/data/DB
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/mmakboub/data/Wordpress
networks:
  inception:
    name: inception
    driver: bridge

