FROM debian:buster

RUN  apt-get update -y && apt-get upgrade -y
RUN  apt-get install -y mariadb-server 
RUN   sed -i 's/^\(bind-address\s.*\)/# \1/' /etc/mysql/mariadb.conf.d/50-server.cnf && echo "bind-address = 0.0.0.0" >> /etc/mysql/mariadb.conf.d/50-server.cnf
# COPY  conf/50-server.cnf	/etc/mysql/mariadb.conf.d/50-server.cnf
COPY  ./tools/scripts.sh .
RUN chmod +x scripts.sh
EXPOSE 3306
CMD ["sh","./scripts.sh"]


# FROM debian:buster

# COPY ./tools/scripts.sh /
# RUN apt-get update -y && apt-get install mariadb-server mariadb-client -y && \
#     sed -i 's/.*#port*./port/' /etc/mysql/mariadb.conf.d/50-server.cnf && \
#     sed -i 's/.*bind-address*./#bind-address/' /etc/mysql/mariadb.conf.d/50-server.cnf && \
#     service mysql start && mysql -u root < rrr

# CMD [ "mysqld" ]