FROM debian:buster

RUN  apt update -y && apt upgrade -y
RUN  sudo apt -y install mariadb-server 
RUN  RUN sed -i 's/^\(bind-address\s.*\)/# \1/' /etc/mysql/mariadb.conf.d/50-server.cnf && echo "bind-address = 0.0.0.0" >> /etc/mysql/mariadb.conf.d/50-server.cnf
# COPY  conf/50-server.cnf	/etc/mysql/mariadb.conf.d/50-server.cnf
COPY  tools/script.sh /
EXPOSE 3306

CMD ["./script.sh"]