FROM  debian:10
RUN apt-get update -y && apt-get upgrade -y
RUN apt-get update -y && apt-get install -y wget
RUN apt-get install -y php-common php7.3-fpm php-mysql curl 
RUN sed -i  's/listen = \/run\/php\/php7.3-fpm.sock/listen = 9000/g' /etc/php/7.3/fpm/pool.d/www.conf
RUN wget https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
RUN chmod +x wp-cli.phar
RUN mv wp-cli.phar /usr/local/bin/wp
RUN mkdir -p /var/www/html
WORKDIR /var/www/html



COPY ./tools/script.sh .
RUN chmod +x script.sh
EXPOSE 9000
# CMD ["sleep", "1000000"]
ENTRYPOINT ["sh", "./script.sh"]
# CMD [ "php-fpm7.3", "-F"]



